[2023-03-13T19:30:01.244+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-13T19:30:01.257+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-13T19:30:01.258+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:30:01.258+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:30:01.258+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:30:01.288+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:03+00:00
[2023-03-13T19:30:01.292+0000] {standard_task_runner.py:55} INFO - Started process 34746 to run task
[2023-03-13T19:30:01.296+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:03+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp2lnj3jjq']
[2023-03-13T19:30:01.299+0000] {standard_task_runner.py:83} INFO - Job 8: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:30:01.362+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [running]> on host dev
[2023-03-13T19:30:01.428+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:03+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:03+00:00
[2023-03-13T19:30:01.430+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:30:01.431+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/usr/bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:30:01.441+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:30:01.443+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: /usr/bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:30:01.443+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:30:01.454+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:30:01.459+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000003, start_date=20230313T193001, end_date=20230313T193001
[2023-03-13T19:30:01.480+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 8 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 34746)
[2023-03-13T19:30:01.507+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:30:01.529+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T19:40:35.071+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-13T19:40:35.084+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-13T19:40:35.084+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:40:35.084+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T19:40:35.084+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T19:40:35.105+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:03+00:00
[2023-03-13T19:40:35.109+0000] {standard_task_runner.py:55} INFO - Started process 36798 to run task
[2023-03-13T19:40:35.113+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:03+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp95e0kral']
[2023-03-13T19:40:35.115+0000] {standard_task_runner.py:83} INFO - Job 56: Subtask Chargement_des_données_in_ELK
[2023-03-13T19:40:35.181+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [running]> on host dev
[2023-03-13T19:40:35.253+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:03+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:03+00:00
[2023-03-13T19:40:35.256+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T19:40:35.256+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash --path.config /etc/logstash/conf.d/data.conf']
[2023-03-13T19:40:35.264+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T19:40:35.266+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T19:40:35.266+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T19:40:35.276+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T19:40:35.281+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000003, start_date=20230313T194035, end_date=20230313T194035
[2023-03-13T19:40:35.299+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 56 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 36798)
[2023-03-13T19:40:35.324+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T19:40:35.344+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:02:01.055+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-13T20:02:01.068+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-13T20:02:01.068+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:02:01.068+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:02:01.068+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:02:01.089+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:03+00:00
[2023-03-13T20:02:01.092+0000] {standard_task_runner.py:55} INFO - Started process 40562 to run task
[2023-03-13T20:02:01.097+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:03+00:00', '--job-id', '168', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpr82nr1kg']
[2023-03-13T20:02:01.099+0000] {standard_task_runner.py:83} INFO - Job 168: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:02:01.172+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [running]> on host dev
[2023-03-13T20:02:01.245+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:03+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:03+00:00
[2023-03-13T20:02:01.247+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:02:01.247+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'bin/logstash -f /home/dev/etc/logstash/conf.d/data.conf']
[2023-03-13T20:02:01.256+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:02:01.258+0000] {subprocess.py:93} INFO - /usr/bin/bash: ligne 1: bin/logstash: Aucun fichier ou dossier de ce type
[2023-03-13T20:02:01.258+0000] {subprocess.py:97} INFO - Command exited with return code 127
[2023-03-13T20:02:01.268+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/dev/airflow/airflow/lib/python3.10/site-packages/airflow/operators/bash.py", line 196, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 127.
[2023-03-13T20:02:01.274+0000] {taskinstance.py:1318} INFO - Marking task as UP_FOR_RETRY. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000003, start_date=20230313T200201, end_date=20230313T200201
[2023-03-13T20:02:01.296+0000] {standard_task_runner.py:100} ERROR - Failed to execute job 168 for task Chargement_des_données_in_ELK (Bash command failed. The command returned a non-zero exit code 127.; 40562)
[2023-03-13T20:02:01.308+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2023-03-13T20:02:01.327+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-13T20:23:39.212+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-13T20:23:39.228+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-13T20:23:39.228+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:23:39.229+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-13T20:23:39.229+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-13T20:23:39.252+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:03+00:00
[2023-03-13T20:23:39.256+0000] {standard_task_runner.py:55} INFO - Started process 44555 to run task
[2023-03-13T20:23:39.260+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:03+00:00', '--job-id', '280', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmp_uzv7fr6']
[2023-03-13T20:23:39.262+0000] {standard_task_runner.py:83} INFO - Job 280: Subtask Chargement_des_données_in_ELK
[2023-03-13T20:23:39.347+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [running]> on host dev
[2023-03-13T20:23:39.460+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:03+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:03+00:00
[2023-03-13T20:23:39.463+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-13T20:23:39.465+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-13T20:23:39.479+0000] {subprocess.py:86} INFO - Output:
[2023-03-13T20:23:39.583+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-13T20:23:39.898+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-13T20:24:06.871+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-13T20:24:07.023+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:07,017][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-13T20:24:07.039+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:07,038][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-13T20:24:07.551+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:07,551][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-13T20:24:10.511+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:10,494][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-13T20:24:11.393+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:11,393][INFO ][org.reflections.Reflections] Reflections took 176 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-13T20:24:13.613+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:13,612][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-13T20:24:14.052+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:14,050][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-13T20:24:14.272+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:14,271][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-13T20:24:14.351+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:14,351][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-13T20:24:14.356+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:14,355][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-13T20:24:14.630+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:14,629][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-13T20:24:14.674+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:14,674][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x682d3b92 run>"}
[2023-03-13T20:24:15.755+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:15,755][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.08}
[2023-03-13T20:24:15.887+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:15,887][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-13T20:24:15.999+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:15,998][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-13T20:24:17.375+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:17,374][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.028233s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-13T20:24:17.559+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:17,558][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.022381s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-13T20:24:18.035+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:18,034][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.450850s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-13T20:24:26.901+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:26,900][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.275565s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-13T20:24:31.518+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:31,518][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-13T20:24:31.685+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:31,685][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-13T20:24:31.750+0000] {subprocess.py:93} INFO - [2023-03-13T20:24:31,749][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-13T20:24:31.904+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-13T20:24:31.933+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000003, start_date=20230313T202339, end_date=20230313T202431
[2023-03-13T20:24:31.987+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-13T20:24:32.004+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-14T09:18:11.421+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-14T09:18:11.436+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-14T09:18:11.437+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:18:11.437+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-14T09:18:11.437+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-14T09:18:11.462+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:03+00:00
[2023-03-14T09:18:11.466+0000] {standard_task_runner.py:55} INFO - Started process 22064 to run task
[2023-03-14T09:18:11.470+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:03+00:00', '--job-id', '524', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmprwlilzjm']
[2023-03-14T09:18:11.472+0000] {standard_task_runner.py:83} INFO - Job 524: Subtask Chargement_des_données_in_ELK
[2023-03-14T09:18:11.543+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [running]> on host dev
[2023-03-14T09:18:11.626+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:03+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:03+00:00
[2023-03-14T09:18:11.629+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-14T09:18:11.629+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-14T09:18:11.638+0000] {subprocess.py:86} INFO - Output:
[2023-03-14T09:18:11.736+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-14T09:18:12.017+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-14T09:18:41.648+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-14T09:18:41.842+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:41,835][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-14T09:18:41.864+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:41,863][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-14T09:18:42.436+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:42,436][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-14T09:18:44.794+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:44,792][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-14T09:18:45.844+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:45,843][INFO ][org.reflections.Reflections] Reflections took 164 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-14T09:18:47.813+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:47,812][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-14T09:18:48.750+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:48,749][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-14T09:18:48.986+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:48,986][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-14T09:18:49.075+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:49,075][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-14T09:18:49.081+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:49,081][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-14T09:18:49.277+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:49,276][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-14T09:18:49.359+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:49,358][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x47866d2 run>"}
[2023-03-14T09:18:50.814+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:50,813][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>1.45}
[2023-03-14T09:18:50.957+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:50,956][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-14T09:18:51.087+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:51,085][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-14T09:18:53.088+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:53,087][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.042131s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-14T09:18:53.338+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:53,338][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.013383s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-14T09:18:53.846+0000] {subprocess.py:93} INFO - [2023-03-14T09:18:53,845][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.453663s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 0
[2023-03-14T09:19:03.412+0000] {subprocess.py:93} INFO - [2023-03-14T09:19:03,412][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.311674s) SELECT * FROM (SELECT * FROM customers) AS "t1" LIMIT 50000 OFFSET 50000
[2023-03-14T09:19:10.189+0000] {subprocess.py:93} INFO - [2023-03-14T09:19:10,189][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-14T09:19:10.265+0000] {subprocess.py:93} INFO - [2023-03-14T09:19:10,264][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-14T09:19:10.326+0000] {subprocess.py:93} INFO - [2023-03-14T09:19:10,325][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-14T09:19:10.715+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-14T09:19:10.748+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000003, start_date=20230314T091811, end_date=20230314T091910
[2023-03-14T09:19:10.781+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-14T09:19:10.795+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-03-15T07:07:11.686+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-15T07:07:11.691+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [queued]>
[2023-03-15T07:07:11.691+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:07:11.691+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 4
[2023-03-15T07:07:11.691+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2023-03-15T07:07:11.702+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): Chargement_des_données_in_ELK> on 2023-03-13 00:00:03+00:00
[2023-03-15T07:07:11.704+0000] {standard_task_runner.py:55} INFO - Started process 116178 to run task
[2023-03-15T07:07:11.705+0000] {standard_task_runner.py:82} INFO - Running: ['airflow', 'tasks', 'run', 'AUTOMATISATION', 'Chargement_des_données_in_ELK', 'scheduled__2023-03-13T00:00:03+00:00', '--job-id', '648', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/tmp/tmpw7gkvcg9']
[2023-03-15T07:07:11.706+0000] {standard_task_runner.py:83} INFO - Job 648: Subtask Chargement_des_données_in_ELK
[2023-03-15T07:07:11.740+0000] {task_command.py:388} INFO - Running <TaskInstance: AUTOMATISATION.Chargement_des_données_in_ELK scheduled__2023-03-13T00:00:03+00:00 [running]> on host dev
[2023-03-15T07:07:11.782+0000] {taskinstance.py:1507} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=AUTOMATISATION
AIRFLOW_CTX_TASK_ID=Chargement_des_données_in_ELK
AIRFLOW_CTX_EXECUTION_DATE=2023-03-13T00:00:03+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-03-13T00:00:03+00:00
[2023-03-15T07:07:11.783+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-03-15T07:07:11.783+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo dev | sudo -S /usr/share/logstash/bin/logstash --path.settings=/etc/logstash/ -f /etc/logstash/conf.d/data.conf']
[2023-03-15T07:07:11.788+0000] {subprocess.py:86} INFO - Output:
[2023-03-15T07:07:11.824+0000] {subprocess.py:93} INFO - [sudo] Mot de passe de dev : Using bundled JDK: /usr/share/logstash/jdk
[2023-03-15T07:07:11.935+0000] {subprocess.py:93} INFO - OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
[2023-03-15T07:07:22.409+0000] {subprocess.py:93} INFO - Sending Logstash logs to /var/log/logstash which is now configured via log4j2.properties
[2023-03-15T07:07:22.468+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:22,466][INFO ][logstash.runner          ] Log4j configuration path used is: /etc/logstash/log4j2.properties
[2023-03-15T07:07:22.474+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:22,473][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"7.15.2", "jruby.version"=>"jruby 9.2.19.0 (2.5.8) 2021-06-15 55810c552b OpenJDK 64-Bit Server VM 11.0.12+7 on 11.0.12+7 +indy +jit [linux-x86_64]"}
[2023-03-15T07:07:22.717+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:22,716][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2023-03-15T07:07:23.572+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:23,571][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2023-03-15T07:07:23.938+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:23,938][INFO ][org.reflections.Reflections] Reflections took 64 ms to scan 1 urls, producing 120 keys and 417 values
[2023-03-15T07:07:24.572+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:24,572][INFO ][logstash.outputs.elasticsearch][main] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost:9200"]}
[2023-03-15T07:07:24.768+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:24,767][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2023-03-15T07:07:24.869+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:24,869][WARN ][logstash.outputs.elasticsearch][main] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2023-03-15T07:07:24.900+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:24,900][INFO ][logstash.outputs.elasticsearch][main] Elasticsearch version determined (7.15.2) {:es_version=>7}
[2023-03-15T07:07:24.902+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:24,902][WARN ][logstash.outputs.elasticsearch][main] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>7}
[2023-03-15T07:07:25.008+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:25,008][INFO ][logstash.outputs.elasticsearch][main] Using a default mapping template {:es_version=>7, :ecs_compatibility=>:disabled}
[2023-03-15T07:07:25.047+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:25,047][INFO ][logstash.javapipeline    ][main] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>50, "pipeline.max_inflight"=>1000, "pipeline.sources"=>["/etc/logstash/conf.d/data.conf"], :thread=>"#<Thread:0x8fb86c6 run>"}
[2023-03-15T07:07:25.561+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:25,561][INFO ][logstash.javapipeline    ][main] Pipeline Java execution initialization time {"seconds"=>0.51}
[2023-03-15T07:07:25.634+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:25,634][INFO ][logstash.javapipeline    ][main] Pipeline started {"pipeline.id"=>"main"}
[2023-03-15T07:07:25.699+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:25,699][INFO ][logstash.agent           ] Pipelines running {:count=>1, :running_pipelines=>[:main], :non_running_pipelines=>[]}
[2023-03-15T07:07:26.383+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:26,383][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.012093s) SELECT CAST(current_setting('server_version_num') AS integer) AS v
[2023-03-15T07:07:26.474+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:26,474][INFO ][logstash.inputs.jdbc     ][main][afa454a497099ce3438919c7cfc7ae10a3b3980082608321cda443e0b5f70dbd] (0.001278s) SELECT count(*) AS "count" FROM (SELECT * FROM customers) AS "t1" LIMIT 1
[2023-03-15T07:07:26.958+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:26,958][INFO ][logstash.javapipeline    ][main] Pipeline terminated {"pipeline.id"=>"main"}
[2023-03-15T07:07:27.239+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:27,238][INFO ][logstash.pipelinesregistry] Removed pipeline from registry successfully {:pipeline_id=>:main}
[2023-03-15T07:07:27.260+0000] {subprocess.py:93} INFO - [2023-03-15T07:07:27,260][INFO ][logstash.runner          ] Logstash shut down.
[2023-03-15T07:07:27.304+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-03-15T07:07:27.319+0000] {taskinstance.py:1318} INFO - Marking task as SUCCESS. dag_id=AUTOMATISATION, task_id=Chargement_des_données_in_ELK, execution_date=20230313T000003, start_date=20230315T070711, end_date=20230315T070727
[2023-03-15T07:07:27.339+0000] {local_task_job.py:208} INFO - Task exited with return code 0
[2023-03-15T07:07:27.346+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
